/** @module Exact workflows owned by release-publication features. */

import { workflowDenoVersion } from "./workflow-toolchain.ts";
import { hjPackageReference } from "./hj-package.ts";
import {
  denoCacheInputs,
  nativeNpmCacheStep,
} from "./github-workflow-cache.ts";

import type {
  ArtifactSchema,
  ExactArtifactInspection,
} from "../api/artifact-inspection.ts";
import type { DetectionContext } from "../api/repository-context.ts";
import { inspectArtifact } from "../artifacts/inspect-artifact.ts";
import { workflowCliArtifact } from "./workflow-cli.ts";
import {
  publishGithubWorkflow,
  publishJsrWorkflow,
  publishNpmWorkflow,
  publishTagWorkflow,
} from "../release/names.ts";

export const releaseWorkflowMarker =
  "# Generated by hj release publication. Do not edit.\n";
const checkout =
  "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1";
const deno =
  "denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5";
const hj = hjPackageReference;

export const publishTagArtifact = {
  path: publishTagWorkflow,
  content: `${releaseWorkflowMarker}name: Publish release tag

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: Existing or missing release tag
        required: false
        type: string

permissions:
  contents: read

concurrency:
  group: hj-release-publish-tag-main
  cancel-in-progress: false

jobs:
  publish-tag-prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    outputs:
      release-needed: \${{ steps.prepare.outputs.release-needed }}
      release-bundle: \${{ steps.prepare.outputs.release-bundle }}
      bundle-digest: \${{ steps.prepare.outputs.bundle-digest }}
    steps:
      - uses: ${checkout}
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false
      - uses: ${deno}
        with:
          deno-version: ${workflowDenoVersion}
${denoCacheInputs}${nativeNpmCacheStep}      - name: Configure Git authentication
        env:
          GH_TOKEN: \${{ github.token }}
        run: gh auth setup-git
      - id: prepare
        env:
          GH_TOKEN: \${{ github.token }}
          HJ_RELEASE_ROUTE: \${{ github.event_name == 'workflow_dispatch' && inputs.tag != '' && 'recovery' || 'usual' }}
          HJ_RELEASE_TAG: \${{ inputs.tag }}
        run: >-
          deno run --no-lock
          --allow-env=PATH,GITHUB_OUTPUT,GITHUB_STEP_SUMMARY,HJ_RELEASE_ROUTE,HJ_RELEASE_TAG,ESBUILD_BINARY_PATH,ESBUILD_WORKER_THREADS
          --allow-read=.,/tmp/opencode
          --allow-write=deno.json,deno.jsonc,CHANGELOG.md,/tmp/opencode,"\${GITHUB_OUTPUT}","\${GITHUB_STEP_SUMMARY}"
          --allow-run=deno,git
          ${hj}
          release publish-tag-prepare
  publish-tag-apply:
    needs: publish-tag-prepare
    if: needs.publish-tag-prepare.outputs.release-needed == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - uses: ${checkout}
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false
      - uses: ${deno}
        with:
          deno-version: ${workflowDenoVersion}
${denoCacheInputs}      - name: Configure Git authentication
        env:
          GH_TOKEN: \${{ github.token }}
        run: gh auth setup-git
      - env:
          GH_TOKEN: \${{ github.token }}
          HJ_RELEASE_ROUTE: \${{ github.event_name == 'workflow_dispatch' && inputs.tag != '' && 'recovery' || 'usual' }}
          HJ_RELEASE_BUNDLE: \${{ needs.publish-tag-prepare.outputs.release-bundle }}
          HJ_RELEASE_BUNDLE_DIGEST: \${{ needs.publish-tag-prepare.outputs.bundle-digest }}
        run: >-
          deno run --no-lock
          --allow-env=PATH,GITHUB_REPOSITORY,GITHUB_RUN_ATTEMPT,GITHUB_RUN_ID,GITHUB_SERVER_URL,GITHUB_STEP_SUMMARY,HJ_RELEASE_BUNDLE,HJ_RELEASE_BUNDLE_DIGEST,HJ_RELEASE_ROUTE
          --allow-read=.,/tmp/opencode
          --allow-write=deno.json,deno.jsonc,CHANGELOG.md,/tmp/opencode,"\${GITHUB_STEP_SUMMARY}"
          --allow-run=deno,gh,git
          ${hj}
          release publish-tag-apply
`,
} as const;

function publisherArtifact(
  path: string,
  name: string,
  job: "jsr" | "github" | "npm",
  command: string,
  permissions: string,
  allowRun: string,
  allowNet = "",
): { readonly path: string; readonly content: string } {
  return {
    path,
    content: `${releaseWorkflowMarker}name: ${name}

on:
  repository_dispatch:
    types: [hj-release-publish-tag-success]
  workflow_dispatch:
    inputs:
      tag:
        description: Existing unprefixed SemVer tag
        required: true
        type: string

permissions:
${permissions}

concurrency:
  group: hj-release-publish-${job}-\${{ github.event.client_payload.tag || inputs.tag }}
  cancel-in-progress: false

jobs:
  publish-${job}:
${
      job === "jsr"
        ? "    if: github.event_name == 'workflow_dispatch' || github.sha == github.event.client_payload.releaseSha\n"
        : ""
    }\
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: ${checkout}
        with:
          ref: \${{ github.event_name == 'repository_dispatch' && github.event.client_payload.releaseSha || inputs.tag }}
          fetch-depth: 0
          persist-credentials: false
      - uses: ${deno}
        with:
          deno-version: ${workflowDenoVersion}
${denoCacheInputs}${
      job === "npm"
        ? `      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "24"
          registry-url: https://registry.npmjs.org
      - name: Select npm CLI
        run: npm install --global npm@11.11.1 --ignore-scripts
`
        : ""
    }      - name: Configure Git authentication
        env:
          GH_TOKEN: \${{ github.token }}
        run: gh auth setup-git
      - env:
          GH_TOKEN: \${{ github.token }}
          GITHUB_REPOSITORY: \${{ github.repository }}
          HJ_RELEASE_ROUTE: \${{ github.event_name == 'repository_dispatch' && 'event' || 'user' }}
          HJ_RELEASE_SCHEMA: \${{ github.event.client_payload.schema }}
          HJ_RELEASE_SHA: \${{ github.event.client_payload.releaseSha }}
          HJ_RELEASE_TAG: \${{ github.event_name == 'repository_dispatch' && github.event.client_payload.tag || inputs.tag }}
          HJ_RELEASE_VERSION: \${{ github.event.client_payload.version }}
${
      job === "npm"
        ? "          NODE_AUTH_TOKEN: \${{ secrets.NPM_TOKEN }}\n"
        : ""
    }        run: >-
          deno run --no-lock
          --allow-env=${
      allowRun.split(",").includes("deno") ? "PATH," : ""
    }GITHUB_REPOSITORY,GITHUB_SHA,HJ_RELEASE_ROUTE,HJ_RELEASE_SCHEMA,HJ_RELEASE_SHA,HJ_RELEASE_TAG,HJ_RELEASE_VERSION
          --allow-read=.
${allowNet ? `${allowNet}\n` : ""}          --allow-run=${allowRun}
          ${hj}
          ${command}
${job === "jsr" ? jsrTagDispatch : ""}\
`,
  };
}

// repository_dispatch starts on main. A later merge must not change the
// workflow identity recorded in the package's signed publication provenance.
const jsrTagDispatch = `  dispatch-tag:
    if: github.event_name == 'repository_dispatch' && github.sha != github.event.client_payload.releaseSha
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
      contents: read
    steps:
      - name: Start publication at the release tag
        env:
          GH_TOKEN: \${{ github.token }}
          GH_REPO: \${{ github.repository }}
          HJ_RELEASE_TAG: \${{ github.event.client_payload.tag }}
        run: >-
          gh workflow run ${publishJsrWorkflow.split("/").at(-1)}
          --repo "$GH_REPO" --ref "$HJ_RELEASE_TAG"
          -f "tag=$HJ_RELEASE_TAG"
`;

export const publishJsrArtifact = publisherArtifact(
  publishJsrWorkflow,
  "Publish JSR package",
  "jsr",
  "release publish-jsr",
  "  contents: read\n  id-token: write",
  "deno,git",
  "          --allow-net=api.jsr.io,jsr.io,rekor.sigstore.dev",
);
export const publishGithubArtifact = publisherArtifact(
  publishGithubWorkflow,
  "Publish GitHub Release",
  "github",
  "release publish-github",
  "  contents: write",
  "gh,git",
);

export const publishNpmArtifact = publisherArtifact(
  publishNpmWorkflow,
  "Publish npm package",
  "npm",
  "release publish-npm",
  "  contents: read\n  id-token: write",
  "deno,git,npm,tar",
  "          --allow-net=registry.npmjs.org",
);

export async function inspectReleaseArtifact(
  context: DetectionContext,
  artifact: { readonly path: string; readonly content: string },
): Promise<ExactArtifactInspection> {
  const observation = await context.files.observe(artifact.path);
  const schema: ArtifactSchema = {
    kind: "file",
    ...workflowCliArtifact(artifact, context, observation),
    mode: 0o644,
  };
  return inspectArtifact(
    schema,
    observation.kind === "file"
      ? { ...observation, mode: schema.mode, access: undefined }
      : observation,
  );
}
