/** @module Exact workflows owned by the GitHub CI feature. */

import { workflowDenoVersion } from "./workflow-toolchain.ts";
import { hjPackageReference } from "./hj-package.ts";

import type {
  ArtifactSchema,
  ExactArtifactInspection,
} from "../api/artifact-inspection.ts";
import type { DetectionContext } from "../api/repository-context.ts";
import { inspectArtifact } from "../artifacts/inspect-artifact.ts";
import { workflowCliArtifact } from "./workflow-cli.ts";

export const githubCiFeatureId = "github-ci";
export const githubCiMarker = "# Generated by hj github-ci. Do not edit.\n";
export const githubCiPermissionResource = "actions-workflow-permission";
export const githubCiPermissionName = "can-approve-pull-request-reviews";

export const githubCiArtifacts = [{
  path: ".github/workflows/hj-ci.yaml",
  content: `${githubCiMarker}name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: ${workflowDenoVersion}
      - run: deno task all
  hj-release-commit-validation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: ${workflowDenoVersion}
      - name: Validate release commits
        env:
          HJ_RELEASE_ROUTE: source-validation
          HJ_SOURCE_BASE_SHA: \${{ github.event.pull_request.base.sha }}
          HJ_SOURCE_HEAD_SHA: \${{ github.event.pull_request.head.sha }}
        run: >-
          deno run --no-lock
          --allow-env=HJ_RELEASE_ROUTE,HJ_SOURCE_BASE_SHA,HJ_SOURCE_HEAD_SHA
          --allow-run=git
          ${hjPackageReference}
          release publish-tag-prepare
`,
}, {
  path: ".github/workflows/hj-deps.yaml",
  content: `${githubCiMarker}name: Update dependencies

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: hj-deps-\${{ github.repository }}
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: \${{ github.event.repository.default_branch }}
          fetch-depth: 0
          persist-credentials: false
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: ${workflowDenoVersion}
      - name: Update dependencies
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -euo pipefail
          gh auth setup-git
          branch="hj/deps"
          base="\${{ github.event.repository.default_branch }}"
          git fetch origin "\${branch}" || true
          remote_branch="\$(git rev-parse --verify "refs/remotes/origin/\${branch}" 2>/dev/null || true)"
          git switch --force-create "\${branch}" "origin/\${base}"
          deno outdated --recursive --update --latest
          git add --all
          if git diff --cached --quiet; then
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --message "chore: update dependencies"
          if [ -n "\${remote_branch}" ]; then
            git push --force-with-lease="refs/heads/\${branch}:\${remote_branch}" \\
              origin "\${branch}:refs/heads/\${branch}"
          else
            git push origin "\${branch}:refs/heads/\${branch}"
          fi
          open_pr_count="$(gh pr list --head "\${branch}" --state open --json url --jq length)"
          if [ "\${open_pr_count}" = "0" ]; then
            gh pr create --base "\${base}" --head "\${branch}" \\
              --title "chore: update dependencies" \\
              --body "Updates all Deno dependencies to their latest versions."
          fi
`,
}] as const;

export async function inspectGithubCiArtifacts(
  context: DetectionContext,
): Promise<readonly ExactArtifactInspection[]> {
  return await Promise.all(githubCiArtifacts.map(async (artifact) => {
    const observation = await context.files.observe(artifact.path);
    const schema: ArtifactSchema = {
      kind: "file",
      ...workflowCliArtifact(artifact, context, observation),
      mode: 0o644,
    };
    // GitHub ignores workflow modes, while shared Git worktrees rewrite them.
    return inspectArtifact(
      schema,
      observation.kind === "file"
        ? { ...observation, mode: schema.mode }
        : observation,
    );
  }));
}

export function githubCiSubject() {
  return {
    kind: "github-workflows",
    identifier: githubCiFeatureId,
  };
}
