/** @module Exact JSR OIDC release workflow and tag validator. */

import type {
  ArtifactSchema,
  ExactArtifactInspection,
} from "../api/artifact-inspection.ts";
import type { DetectionContext } from "../api/repository-context.ts";
import { inspectArtifact } from "../artifacts/inspect-artifact.ts";

export const jsrReleaseFeatureId = "jsr-release";
export const jsrReleaseMarker = "# Generated by hj jsr-release. Do not edit.\n";
export const jsrReleasePath = ".github/workflows/hj-release.yaml";

/** Runs without environment permission so the tag is passed as an argument. */
export const jsrReleaseValidationScript =
  `import { parse } from "npm:jsonc-parser@3.3.1";const fail=(message)=>{console.error(message);Deno.exit(1)};const tag=Deno.args[0];const semver=/^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:\\.(?:0|[1-9]\\d*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$/;if(!semver.test(tag??""))fail("Release tag must be strict unprefixed SemVer.");const files=[];for(const path of ["deno.json","deno.jsonc"]){try{const info=await Deno.stat(path);if(!info.isFile)fail(path+" must be a regular file.");files.push(path)}catch(error){if(error instanceof Deno.errors.NotFound)continue;throw error}}if(files.length!==1)fail("Exactly one regular deno.json or deno.jsonc is required.");const errors=[];const value=parse(await Deno.readTextFile(files[0]),errors,{allowTrailingComma:true,disallowComments:false});if(errors.length>0||value===null||Array.isArray(value)||typeof value!=="object"||typeof value.version!=="string"||!semver.test(value.version))fail("Deno config must contain a strict SemVer version.");if(tag!==value.version)fail("Release tag must equal the Deno config version.");`;

export const jsrReleaseArtifact = {
  path: jsrReleasePath,
  content: `${jsrReleaseMarker}name: Publish JSR package

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  id-token: write

concurrency:
  group: hj-jsr-release-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: latest
      - name: Validate release tag
        run: deno eval --allow-read=deno.json,deno.jsonc '${jsrReleaseValidationScript}' -- "\${GITHUB_REF_NAME}"
      - run: deno task publish-check
      - run: deno publish
`,
} as const;

export async function inspectJsrReleaseArtifact(
  context: DetectionContext,
): Promise<ExactArtifactInspection> {
  const schema: ArtifactSchema = {
    kind: "file",
    ...jsrReleaseArtifact,
    mode: 0o644,
  };
  const observation = await context.files.observe(jsrReleasePath);
  return inspectArtifact(
    schema,
    observation.kind === "file"
      ? { ...observation, mode: schema.mode }
      : observation,
  );
}

export function jsrReleaseSubject() {
  return { kind: "github-workflow", identifier: jsrReleasePath };
}
