import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import {
  jsrReleaseArtifact,
  jsrReleaseValidationScript,
} from "./jsr-release-artifacts.ts";

Deno.test("jsr-release workflow is the exact OIDC publishing snapshot", () => {
  assertEquals(jsrReleaseArtifact.path, ".github/workflows/hj-release.yaml");
  assertStringIncludes(
    jsrReleaseArtifact.content,
    "# Generated by hj jsr-release. Do not edit.",
  );
  assertStringIncludes(jsrReleaseArtifact.content, 'tags:\n      - "*"');
  assertStringIncludes(
    jsrReleaseArtifact.content,
    "contents: read\n  id-token: write",
  );
  assertStringIncludes(jsrReleaseArtifact.content, "runs-on: ubuntu-latest");
  assertStringIncludes(
    jsrReleaseArtifact.content,
    "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1",
  );
  assertStringIncludes(
    jsrReleaseArtifact.content,
    "denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5",
  );
  assertStringIncludes(jsrReleaseArtifact.content, "deno-version: latest");
  assertStringIncludes(jsrReleaseArtifact.content, '-- "${GITHUB_REF_NAME}"');
  assert(!jsrReleaseArtifact.content.includes("${{ GITHUB_REF_NAME }}"));
  assertStringIncludes(
    jsrReleaseArtifact.content,
    "deno task publish-check\n      - run: deno publish",
  );
  assert(!jsrReleaseArtifact.content.includes("GH_TOKEN"));
  assert(!jsrReleaseArtifact.content.includes("--allow-dirty"));
  assert(!jsrReleaseArtifact.content.includes("--no-provenance"));
});

Deno.test("jsr-release validator accepts exact stable and prerelease config versions", async () => {
  await withConfig("deno.json", '{"version":"1.2.3"}', "1.2.3", true);
  await withConfig(
    "deno.jsonc",
    '// comment\n{"version": "1.2.3-rc.1",}',
    "1.2.3-rc.1",
    true,
  );
});

Deno.test("jsr-release validator rejects invalid tag and config states", async () => {
  await withConfig("deno.json", '{"version":"1.2.3"}', "v1.2.3", false);
  await withConfig("deno.json", '{"version":"1.2.3"}', "1.2.4", false);
  await withConfig("deno.json", '{"version":"bad"}', "1.2.3", false);
  await withConfig("deno.json", "{", "1.2.3", false);
  await withConfig("deno.json", '{"version":"1.2.3"}', "1.2", false, true);
  await withDirectory("deno.json", "1.2.3");
});

async function withConfig(
  file: "deno.json" | "deno.jsonc",
  content: string,
  tag: string,
  expected: boolean,
  duplicate = false,
) {
  const root = await Deno.makeTempDir({
    dir: "/tmp/opencode",
    prefix: "hj-release-validator-",
  });
  try {
    await Deno.writeTextFile(`${root}/${file}`, content);
    if (duplicate) {
      await Deno.writeTextFile(`${root}/deno.jsonc`, '{"version":"1.2.3"}');
    }
    const result = await new Deno.Command("deno", {
      args: [
        "eval",
        "--allow-read=deno.json,deno.jsonc",
        jsrReleaseValidationScript,
        "--",
        tag,
      ],
      cwd: root,
    }).output();
    assertEquals(result.success, expected);
  } finally {
    await Deno.remove(root, { recursive: true });
  }
}

async function withDirectory(name: string, tag: string) {
  const root = await Deno.makeTempDir({
    dir: "/tmp/opencode",
    prefix: "hj-release-validator-",
  });
  try {
    await Deno.mkdir(`${root}/${name}`);
    const result = await new Deno.Command("deno", {
      args: [
        "eval",
        "--allow-read=deno.json,deno.jsonc",
        jsrReleaseValidationScript,
        "--",
        tag,
      ],
      cwd: root,
    }).output();
    assertEquals(result.success, false);
  } finally {
    await Deno.remove(root, { recursive: true });
  }
}
