/** Assemble and finalize this CLI's native, dependency-complete npm archive. */
import { build } from "@deno/dnt";
import { createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";
import { fileURLToPath } from "node:url";
import { nativeBuildOptions } from "./options.ts";

const root = new URL("../../", import.meta.url);
const output = new URL(".hj/npm/", root);
const tools = new URL(".hj/npm-tools/", root);
const packing = new URL(".hj/npm-packing/", root);
const config = JSON.parse(await Deno.readTextFile(new URL("deno.json", root)));
const sourceLock = JSON.parse(
  await Deno.readTextFile(new URL("deno.lock", root)),
);
const dependencyRoot = new URL("./dependencies/", import.meta.url);
const dependencyManifest = JSON.parse(
  await Deno.readTextFile(new URL("package.json", dependencyRoot)),
);
const dependencyLockText = await Deno.readTextFile(
  new URL("package-lock.json", dependencyRoot),
);
const dependencyLock = JSON.parse(dependencyLockText);
if (
  sourceLock.specifiers[config.imports["@std/path"]] !==
    dependencyManifest.dependencies["@jsr/std__path"]
) {
  throw new Error("The direct JSR mapping differs from the application lock.");
}
const environment = Deno.env.toObject();
const marker = "Generated by scripts/build-npm.ts\n";
if (Deno.build.os !== "linux" || Deno.build.arch !== "x86_64") {
  throw new Error("The native npm build currently supports Linux x64 only.");
}
if (
  !(await command("node", [
    "-p",
    "process.report.getReport().header.glibcVersionRuntime || ''",
  ], root)).trim()
) {
  throw new Error("The native npm build currently supports glibc only.");
}
for (const [path, entry] of Object.entries(dependencyLock.packages)) {
  if (!path) continue;
  const item = entry as { version: string; integrity: string };
  const name = path.split("node_modules/").at(-1)!;
  const jsrName = name.startsWith("@jsr/")
    ? "@" + name.slice(5).replace("__", "/")
    : undefined;
  const locked = jsrName
    ? sourceLock.jsr[`${jsrName}@${item.version}`]
    : Object.entries(sourceLock.npm).find(([key]) =>
      key.split("_")[0] === `${name}@${item.version}`
    )?.[1] as { integrity: string } | undefined;
  if (!locked || (!jsrName && locked.integrity !== item.integrity)) {
    throw new Error(
      `npm dependency ${name}@${item.version} differs from deno.lock. Update both locks deliberately.`,
    );
  }
}
const sha = environment.HJ_RELEASE_SHA ??
  (await command("git", ["rev-parse", "HEAD"], root)).trim();
if (!/^[a-f0-9]{40}$/.test(sha)) throw new Error("Invalid npm build Git SHA.");
if (
  environment.HJ_RELEASE_VERSION &&
  environment.HJ_RELEASE_VERSION !== config.version
) {
  throw new Error("npm build version differs from the requested release.");
}
await reset(output);
await reset(tools);
await reset(packing);
const userConfig = new URL("empty-user.npmrc", tools);
const globalConfig = new URL("empty-global.npmrc", tools);
await Deno.writeTextFile(userConfig, "");
await Deno.writeTextFile(globalConfig, "");
const npmEnvironment = {
  ...Object.fromEntries(
    Object.entries(environment).filter(([key]) =>
      !key.toLowerCase().startsWith("npm_config_") &&
      !["NODE_AUTH_TOKEN", "NPM_TOKEN"].includes(key)
    ),
  ),
  npm_config_cache: fileURLToPath(new URL("cache/", tools)),
  npm_config_userconfig: fileURLToPath(userConfig),
  npm_config_globalconfig: fileURLToPath(globalConfig),
  npm_config_registry: "https://registry.npmjs.org/",
  npm_config_update_notifier: "false",
  npm_config_audit: "false",
  npm_config_fund: "false",
};
// The host npm only bootstraps an integrity-locked npm version and type definitions.
await copyManifest(new URL("./tools/", import.meta.url), tools);
await command("npm", ["ci", "--ignore-scripts"], tools, npmEnvironment);
const npmCli = fileURLToPath(new URL("node_modules/npm/bin/npm-cli.js", tools));
const npm = (args: string[], cwd = output) =>
  command("node", [npmCli, ...args], cwd, npmEnvironment);
if ((await npm(["--version"])).trim() !== "11.11.1") {
  throw new Error("Wrong npm build tool version.");
}
await copyManifest(dependencyRoot, output);
await npm(["ci", "--ignore-scripts"]);
await npm(["ls", "--omit=dev", "--all", "--json"]);
if (
  await Deno.readTextFile(new URL("package-lock.json", output)) !==
    dependencyLockText
) {
  throw new Error("Frozen dependency installation changed the lock.");
}
// Supply build-only Node types without adding optional type peers to the runtime graph.
const types = new URL("node_modules/@types/node", output);
await Deno.mkdir(new URL("node_modules/@types/", output), { recursive: true });
await Deno.symlink(
  fileURLToPath(new URL("node_modules/@types/node", tools)),
  types,
);
const archiveName = `${
  config.name.slice(1).replace("/", "-")
}-${config.version}.tgz`;
await build(nativeBuildOptions(root, output, {
  name: config.name,
  version: config.version,
  gitHead: sha,
  description: "Repository tools for Deno, Node.js and Bun.",
  license: config.license,
  type: "module",
  repository: {
    type: "git",
    url: "git+https://github.com/hugojosefson/cli.git",
  },
  engines: { node: ">=24", bun: ">=1.4.2" },
  os: ["linux"],
  cpu: ["x64"],
  libc: ["glibc"],
  publishConfig: { access: "public", registry: "https://registry.npmjs.org/" },
  hjNpmArchive: archiveName,
}));
await Deno.remove(types);
const manifestPath = new URL("package.json", output);
const manifest = JSON.parse(await Deno.readTextFile(manifestPath));
for (
  const key of [
    "optionalDependencies",
    "peerDependencies",
    "bundledDependencies",
  ]
) {
  if (manifest[key] !== undefined) {
    throw new Error(`Unhandled ${key} in the emitted npm manifest.`);
  }
}
if (
  !isDeepStrictEqual(manifest.dependencies, dependencyManifest.dependencies)
) {
  throw new Error(
    "Emitted runtime dependencies differ from the frozen npm build manifest.",
  );
}
manifest.bundleDependencies = Object.keys(manifest.dependencies).sort();
manifest.files = ["esm", "LICENSE", "README.md", "npm-dependencies.lock.json"];
await Deno.writeTextFile(
  manifestPath,
  JSON.stringify(manifest, null, 2) + "\n",
);
await Deno.copyFile(new URL("LICENSE", root), new URL("LICENSE", output));
await Deno.writeTextFile(
  new URL("npm-dependencies.lock.json", output),
  dependencyLockText,
);
await Deno.writeTextFile(
  new URL("README.md", output),
  "# hj\n\nRepository tools for Linux x64 glibc. Requires Node.js 24+ or Bun 1.4.2+.\n\nRun `npx @hugojosefson/cli --help` or `bunx --bun @hugojosefson/cli --help`. Ordinary commands run natively. Commands that run Deno project tasks need a compatible Deno executable.\n\nSee https://github.com/hugojosefson/cli for documentation.\n",
);
const initial = JSON.parse(
  await npm([
    "pack",
    "--json",
    "--ignore-scripts",
    "--pack-destination",
    fileURLToPath(packing),
  ]),
)[0];
await command("tar", [
  "-xzf",
  fileURLToPath(new URL(initial.filename, packing)),
  "-C",
  fileURLToPath(packing),
], root);
const packedRoot = new URL("package/", packing);
manifest.hjBundledDependencies = manifest.dependencies;
delete manifest.dependencies;
delete manifest.bundleDependencies;
delete manifest.scripts;
const finalManifest = JSON.stringify(manifest, null, 2) + "\n";
await Deno.writeTextFile(new URL("package.json", packedRoot), finalManifest);
await Deno.writeTextFile(manifestPath, finalManifest);
// Keep private dependencies outside npm's root dependency pruning on later npx runs.
await Deno.rename(
  new URL("node_modules", packedRoot),
  new URL("esm/node_modules", packedRoot),
);
await Deno.rename(
  new URL("node_modules", output),
  new URL("esm/node_modules", output),
);
const archive = new URL(archiveName, output);
await command("tar", [
  "--sort=name",
  "--mtime=@0",
  "--mode=u+rwX,go+rX,go-w",
  "--owner=0",
  "--group=0",
  "--numeric-owner",
  "--format=gnu",
  "-czf",
  fileURLToPath(archive),
  "-C",
  fileURLToPath(packing),
  "package",
], root);
const report = JSON.parse(
  await npm([
    "pack",
    "--dry-run",
    "--json",
    "--ignore-scripts",
    fileURLToPath(archive),
  ]),
)[0];
const bytes = await Deno.readFile(archive);
const integrity = `sha512-${
  createHash("sha512").update(bytes).digest("base64")
}`;
if (report.integrity !== integrity) {
  throw new Error("npm inspection differs from final archive bytes.");
}
await Deno.writeTextFile(
  new URL("artifact.json", output),
  JSON.stringify({ ...report, gitHead: sha }, null, 2) + "\n",
);
console.log(
  `Built ${
    fileURLToPath(archive)
  } (${bytes.length} bytes). No package was published.`,
);

async function reset(directory: URL) {
  const parent = new URL(".hj/", root);
  try {
    if (!(await Deno.lstat(parent)).isDirectory) {
      throw new Error(".hj must be a real directory.");
    }
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
    await Deno.mkdir(parent);
  }
  try {
    if (
      !(await Deno.lstat(directory)).isDirectory ||
      !(await Deno.lstat(new URL(".hj-build", directory))).isFile ||
      await Deno.readTextFile(new URL(".hj-build", directory)) !== marker
    ) {
      throw new Error("The npm output directory is not owned by this build.");
    }
    await Deno.remove(directory, { recursive: true });
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
    try {
      await Deno.lstat(directory);
      throw new Error(
        "The npm output directory exists without its build marker.",
      );
    } catch (error) {
      if (!(error instanceof Deno.errors.NotFound)) throw error;
    }
  }
  await Deno.mkdir(directory, { recursive: true });
  await Deno.writeTextFile(new URL(".hj-build", directory), marker);
}
async function copyManifest(from: URL, to: URL) {
  for (const name of ["package.json", "package-lock.json"]) {
    await Deno.copyFile(new URL(name, from), new URL(name, to));
  }
}
async function command(
  name: string,
  args: string[],
  cwd: URL,
  env = environment,
) {
  const result = await new Deno.Command(name, {
    args,
    cwd,
    clearEnv: true,
    env,
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!result.success) {
    throw new Error(
      `${name} failed (${result.code}): ${
        new TextDecoder().decode(result.stderr)
      }`,
    );
  }
  return new TextDecoder().decode(result.stdout);
}
