/** Build this repository's optional npm launcher without publishing it. */
const root = new URL("../", import.meta.url);
const output = new URL(".hj/npm/", root);
const config = JSON.parse(await Deno.readTextFile(new URL("deno.json", root)));
const git = async (args: string[]) => {
  const result = await new Deno.Command("git", {
    args,
    cwd: root,
    clearEnv: true,
    env: { PATH: Deno.env.get("PATH") ?? "" },
  }).output();
  if (!result.success) {
    throw new Error("Cannot read Git data for the npm build.");
  }
  return new TextDecoder().decode(result.stdout).trim();
};
const sha = Deno.env.get("HJ_RELEASE_SHA") ?? await git(["rev-parse", "HEAD"]);
const marker = "Generated by scripts/build-npm.ts\n";
try {
  if (await Deno.readTextFile(new URL(".hj-build", output)) !== marker) {
    throw new Error("The npm output directory is not owned by this build.");
  }
  await Deno.remove(output, { recursive: true });
} catch (error) {
  if (!(error instanceof Deno.errors.NotFound)) throw error;
  try {
    await Deno.lstat(output);
    throw new Error(
      "The npm output directory already exists without its build marker.",
    );
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
}
await Deno.mkdir(new URL("bin/", output), { recursive: true });
await Deno.writeTextFile(new URL(".hj-build", output), marker);
const tracked = (await git(["ls-files", "-z"])).split("\0").filter(Boolean);
for (const path of tracked) {
  if (
    !(["deno.json", "deno.lock", "toolchain.json", "LICENSE"].includes(path) ||
      path.startsWith("src/")) || /(?:_test|test-fixtures)\.ts$/.test(path)
  ) continue;
  const source = new URL(path, root);
  if (!(await Deno.lstat(source)).isFile) {
    throw new Error("npm source must be a regular file.");
  }
  const destination = new URL(`source/${path}`, output);
  await Deno.mkdir(new URL("./", destination), { recursive: true });
  await Deno.copyFile(source, destination);
}
const launcher = `#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const config = fileURLToPath(new URL("../source/deno.json", import.meta.url));
const cli = fileURLToPath(new URL("../source/src/cli/cli.ts", import.meta.url));
const child = spawnSync("deno", ["run", "--frozen", "--allow-all", "--config", config, cli, ...process.argv.slice(2)], { stdio: "inherit" });
if (child.error) { console.error("hj requires Deno on PATH. Install Deno from https://deno.com/."); process.exit(1); }
process.exit(child.status ?? 1);
`;
await Deno.writeTextFile(new URL("bin/hj.js", output), launcher, {
  mode: 0o755,
});
await Deno.writeTextFile(
  new URL("package.json", output),
  JSON.stringify(
    {
      name: config.name,
      version: config.version,
      gitHead: sha,
      description: "hj repository tools. Requires Deno on PATH.",
      license: config.license,
      type: "module",
      bin: { hj: "bin/hj.js" },
      files: ["bin", "source", "README.md"],
      repository: {
        type: "git",
        url: "git+https://github.com/hugojosefson/cli.git",
      },
      engines: { node: ">=22" },
      publishConfig: {
        access: "public",
        registry: "https://registry.npmjs.org/",
      },
    },
    null,
    2,
  ) + "\n",
);
await Deno.writeTextFile(
  new URL("README.md", output),
  "# hj npm build example\n\nThis launcher requires Node.js and Deno on PATH. It runs the packaged CLI source with full Deno permissions.\n\nInstall this archive with `npm install --global ./archive.tgz`, then run `hj --help`.\n",
);
console.log("Built .hj/npm. No package was published.");
