/** Regenerate the README example from this checkout's local feature detection. */
import { formatFeatureStatus } from "../src/cli/format-features.ts";
import { builtInFeatureRegistry } from "../src/features/built-in-feature-registry.ts";
import { buildReadmeText } from "../src/readme/build-readme.ts";
import { LocalFileReader } from "../src/repository/local-file-reader.ts";
import { LocalGitReader } from "../src/repository/local-git-reader.ts";

const root = new URL("../", import.meta.url);
const selected = new Set(["deno-cli", "deno-lib", "deno-test", "git-ignore"]);
const registry = {
  ...builtInFeatureRegistry,
  features: builtInFeatureRegistry.features.filter((feature) =>
    selected.has(feature.metadata.id)
  ),
};
const context = {
  repositoryRoot: root,
  files: new LocalFileReader(root),
  git: new LocalGitReader(root),
};
const detections = new Map(
  await Promise.all(
    registry.features.map(async (feature) =>
      [feature.metadata.id, await feature.detect(context)] as const
    ),
  ),
);
const output = formatFeatureStatus(registry, detections, true);
const plain = formatFeatureStatus(registry, detections);
const generated = new Map([
  ["readme/generated/features.svg", terminalSvg(output, plain)],
  [
    "readme/generated/features.md",
    "<!-- Generated by deno task readme-example. Do not edit. -->\n\n" +
    `![${
      registry.features.map((feature) => {
        const id = feature.metadata.id;
        return `${id}: ${detections.get(id)!.state}`;
      }).join("; ")
    }.](features.svg)\n`,
  ],
]);

if (Deno.args.length && Deno.args.join(" ") !== "--check") {
  throw new Error("Usage: deno task readme-example [--check]");
}
if (Deno.args[0] === "--check") {
  // Generate the complete document from fresh fragments, without changing the
  // checkout or depending on the committed example's current contents.
  generated.set(
    "README.md",
    await buildReadmeText(
      root,
      await Deno.readTextFile(new URL("readme/README.md", root)),
      undefined,
      {
        readFile: async (path) =>
          generated.get(path) ?? await Deno.readTextFile(new URL(path, root)),
      },
    ),
  );
  const stale = [];
  for (const [path, content] of generated) {
    let existing;
    try {
      existing = await Deno.readTextFile(new URL(path, root));
    } catch (error) {
      if (!(error instanceof Deno.errors.NotFound)) throw error;
    }
    if (existing !== content) stale.push(path);
  }
  if (stale.length) {
    throw new Error(
      `Generated documentation differs: ${stale.join(", ")}. ` +
        "Run deno task readme-example && deno task readme.",
    );
  }
  console.log("Fresh feature example and README match the committed files.");
} else {
  await Deno.mkdir(new URL("readme/generated/", root), { recursive: true });
  for (const [path, content] of generated) {
    await Deno.writeTextFile(new URL(path, root), content);
  }
}

/** Render the CLI's small ANSI palette as an accessible terminal image. */
function terminalSvg(output: string, plain: string): string {
  const lines = output.split("\n");
  const width = Math.max(...plain.split("\n").map((line) => line.length)) * 8 +
    32;
  const height = (lines.length + 2) * 22 + 24;
  const colors: Record<string, string> = {
    "0": 'fill="#e6edf3"',
    "1": 'fill="#e6edf3" font-weight="bold"',
    "2": 'fill="#919ba6"',
    "31": 'fill="#ff7b72"',
    "32": 'fill="#7ee787"',
    "33": 'fill="#e3b341"',
    "36": 'fill="#79c0ff"',
  };
  const rows = lines.map((line, index) => {
    let style = colors["0"];
    let column = 0;
    // deno-lint-ignore no-control-regex -- Parse terminal ANSI style codes.
    const spans = line.split(/(\x1b\[\d+m)/).map((part) => {
      // deno-lint-ignore no-control-regex -- Parse terminal ANSI style codes.
      const code = part.match(/^\x1b\[(\d+)m$/)?.[1];
      if (code !== undefined) {
        style = colors[code] ?? colors["0"];
        return "";
      }
      const x = 16 + column * 8;
      column += part.length;
      return part
        ? `<tspan x="${x}" textLength="${
          part.length * 8
        }" lengthAdjust="spacingAndGlyphs" ${style}>${xml(part)}</tspan>`
        : "";
    }).join("");
    return `  <text x="16" y="${(index + 3) * 22}">${spans}</text>`;
  });
  return [
    "<!-- Generated by deno task readme-example. Do not edit. -->",
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title description">`,
    '  <title id="title">hj repo features: selected rows from this repository</title>',
    `  <desc id="description">${xml(plain)}</desc>`,
    '  <rect width="100%" height="100%" rx="8" fill="#0d1117"/>',
    '  <g font-family="DejaVu Sans Mono, monospace" font-size="13" xml:space="preserve">',
    '  <text x="16" y="24" fill="#e6edf3">$ hj repo features</text>',
    ...rows,
    "  </g>",
    "</svg>\n",
  ].join("\n");
}

function xml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}
