/** Keep generated test files inside explicitly owned, nonsymlink directories. */
import { lstat, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { isNotFound } from "../../src/runtime/errors.ts";
const marker = "Generated by hj shared test tooling\n";
async function info(url: URL) {
  try {
    return await lstat(new URL(url.href.replace(/\/$/, "")));
  } catch (error) {
    if (isNotFound(error)) return undefined;
    throw error;
  }
}
export async function prepareTestDirectory(
  root: URL,
  name: "test" | "test-tools" | "test-results",
  clear = false,
): Promise<URL> {
  const parent = new URL(".hj/", root);
  const parentInfo = await info(parent);
  if (parentInfo && !parentInfo.isDirectory()) {
    throw new Error(".hj must be a real directory");
  }
  const directory = new URL(`${name}/`, parent);
  const existing = await info(directory);
  const markerPath = new URL(".hj-test-build", directory);
  if (existing) {
    if (
      !existing.isDirectory() || !(await info(markerPath))?.isFile() ||
      await readFile(markerPath, "utf8") !== marker
    ) {
      throw new Error(
        `Refusing to replace unowned test directory: ${directory.pathname}`,
      );
    }
    if (clear) await rm(directory, { recursive: true });
  }
  if (!existing || clear) await mkdir(directory, { recursive: true });
  await writeFile(markerPath, marker);
  return directory;
}
